### ISSUE TITLE
Cannot resolve symbol 'amazonaws'

### ISSUE THREAD

**Issue by ghost** [dhorions/lambdaDynamodbScaler#4]
Hi,
I cant import amazonaws in scaler.java.
How can i fix this?
Thanks

**Comment by dhorions** [comment]
Make sure you have the depency for the aws libraries included in your project.

I also created a course on how to create lambda functions in java using maven, that should help you get on your way, you can access that [here](https://www.udemy.com/serverless-api-aws-lambda-for-java-developers/?couponCode=GITHUB).

**Comment by ghost** [comment]
I fixed this.
Thanks!
